/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerSeasonStats = IDL.Record({
  'id' : IDL.Nat,
  'mepAvg' : IDL.Opt(IDL.Float64),
  'goalsPerGame' : IDL.Opt(IDL.Float64),
  'technicalFaults' : IDL.Opt(IDL.Nat),
  'mepTotal' : IDL.Opt(IDL.Float64),
  'goals7m' : IDL.Opt(IDL.Nat),
  'playerId' : IDL.Nat,
  'provoked7m' : IDL.Opt(IDL.Nat),
  'fieldShots' : IDL.Opt(IDL.Nat),
  'assistsPerGame' : IDL.Opt(IDL.Float64),
  'season' : IDL.Text,
  'percent7m' : IDL.Opt(IDL.Float64),
  'fieldGoals' : IDL.Opt(IDL.Nat),
  'totalYellowCards' : IDL.Opt(IDL.Nat),
  'shots7m' : IDL.Opt(IDL.Nat),
  'totalSaves' : IDL.Opt(IDL.Nat),
  'totalShots' : IDL.Opt(IDL.Nat),
  'totalGoals' : IDL.Opt(IDL.Nat),
  'awarded7m' : IDL.Opt(IDL.Nat),
  'matchesPlayed' : IDL.Nat,
  'fieldGoalPercent' : IDL.Opt(IDL.Float64),
  'totalAssists' : IDL.Opt(IDL.Nat),
  'totalRedCards' : IDL.Opt(IDL.Nat),
  'shootingPercent' : IDL.Opt(IDL.Float64),
  'totalTwoMin' : IDL.Opt(IDL.Nat),
  'totalMinutes' : IDL.Opt(IDL.Nat),
});
export const FeedEventType = IDL.Variant({
  'NextMatch' : IDL.Null,
  'GoalsScored' : IDL.Null,
  'GamePlayed' : IDL.Null,
  'MinutesPlayed' : IDL.Null,
  'YellowCard' : IDL.Null,
  'SeasonAvgUpdated' : IDL.Null,
  'TwoMinSuspension' : IDL.Null,
});
export const FeedEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'playerId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'matchId' : IDL.Opt(IDL.Nat),
  'statValue' : IDL.Opt(IDL.Int),
  'eventType' : FeedEventType,
});
export const Position = IDL.Variant({
  'Linje' : IDL.Null,
  'VenstreKant' : IDL.Null,
  'Keeper' : IDL.Null,
  'Bakspiller' : IDL.Null,
  'HoyreKant' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'nationality' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'jerseyNumber' : IDL.Opt(IDL.Nat),
  'imageUrl' : IDL.Opt(IDL.Text),
  'teamId' : IDL.Nat,
  'position' : Position,
});
export const MatchStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Finished' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : MatchStatus,
  'venue' : IDL.Opt(IDL.Text),
  'awayTeamId' : IDL.Nat,
  'homeTeamId' : IDL.Nat,
  'competition' : IDL.Text,
});
export const PlayerMatchStats = IDL.Record({
  'id' : IDL.Nat,
  'blueCards' : IDL.Opt(IDL.Nat),
  'minutesPlayed' : IDL.Opt(IDL.Nat),
  'assists' : IDL.Opt(IDL.Nat),
  'twoMinSuspensions' : IDL.Opt(IDL.Nat),
  'playerId' : IDL.Nat,
  'sevenMeterGoals' : IDL.Opt(IDL.Nat),
  'yellowCards' : IDL.Opt(IDL.Nat),
  'turnovers' : IDL.Opt(IDL.Nat),
  'sevenMeterAttempts' : IDL.Opt(IDL.Nat),
  'saves' : IDL.Opt(IDL.Nat),
  'shotPct' : IDL.Opt(IDL.Float64),
  'shots' : IDL.Opt(IDL.Nat),
  'matchId' : IDL.Nat,
  'goals' : IDL.Opt(IDL.Nat),
  'savePct' : IDL.Opt(IDL.Float64),
  'redCards' : IDL.Opt(IDL.Nat),
});
export const ProfixioStatus = IDL.Record({
  'dataSource' : IDL.Text,
  'liveStatsCount' : IDL.Nat,
  'isLive' : IDL.Bool,
  'message' : IDL.Text,
  'lastSync' : IDL.Opt(IDL.Int),
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'goalDifference' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'matchesPlayed' : IDL.Opt(IDL.Nat),
  'standingsRank' : IDL.Opt(IDL.Nat),
  'points' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  'followPlayer' : IDL.Func([IDL.Nat], [], []),
  'getAllPlayerSeasonStats' : IDL.Func(
      [],
      [IDL.Vec(PlayerSeasonStats)],
      ['query'],
    ),
  'getDataStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'playersWithStats' : IDL.Nat,
          'dataSource' : IDL.Text,
          'liveStatsCount' : IDL.Nat,
          'playerCount' : IDL.Nat,
          'teamCount' : IDL.Nat,
          'statsSource' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getFeedEvents' : IDL.Func([], [IDL.Vec(FeedEvent)], ['query']),
  'getFollowedPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getNextMatchForTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerMatchStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PlayerMatchStats)],
      ['query'],
    ),
  'getPlayerSeasonStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerSeasonStats)],
      ['query'],
    ),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getProfixioStatus' : IDL.Func([], [ProfixioStatus], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getUpcomingMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'initUserFollows' : IDL.Func([], [], []),
  'isFollowing' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'refreshFromProfixio' : IDL.Func([], [IDL.Text], []),
  'refreshPlayerStats' : IDL.Func([], [IDL.Text], []),
  'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
  'searchTeams' : IDL.Func([IDL.Text], [IDL.Vec(Team)], ['query']),
  'unfollowPlayer' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerSeasonStats = IDL.Record({
    'id' : IDL.Nat,
    'mepAvg' : IDL.Opt(IDL.Float64),
    'goalsPerGame' : IDL.Opt(IDL.Float64),
    'technicalFaults' : IDL.Opt(IDL.Nat),
    'mepTotal' : IDL.Opt(IDL.Float64),
    'goals7m' : IDL.Opt(IDL.Nat),
    'playerId' : IDL.Nat,
    'provoked7m' : IDL.Opt(IDL.Nat),
    'fieldShots' : IDL.Opt(IDL.Nat),
    'assistsPerGame' : IDL.Opt(IDL.Float64),
    'season' : IDL.Text,
    'percent7m' : IDL.Opt(IDL.Float64),
    'fieldGoals' : IDL.Opt(IDL.Nat),
    'totalYellowCards' : IDL.Opt(IDL.Nat),
    'shots7m' : IDL.Opt(IDL.Nat),
    'totalSaves' : IDL.Opt(IDL.Nat),
    'totalShots' : IDL.Opt(IDL.Nat),
    'totalGoals' : IDL.Opt(IDL.Nat),
    'awarded7m' : IDL.Opt(IDL.Nat),
    'matchesPlayed' : IDL.Nat,
    'fieldGoalPercent' : IDL.Opt(IDL.Float64),
    'totalAssists' : IDL.Opt(IDL.Nat),
    'totalRedCards' : IDL.Opt(IDL.Nat),
    'shootingPercent' : IDL.Opt(IDL.Float64),
    'totalTwoMin' : IDL.Opt(IDL.Nat),
    'totalMinutes' : IDL.Opt(IDL.Nat),
  });
  const FeedEventType = IDL.Variant({
    'NextMatch' : IDL.Null,
    'GoalsScored' : IDL.Null,
    'GamePlayed' : IDL.Null,
    'MinutesPlayed' : IDL.Null,
    'YellowCard' : IDL.Null,
    'SeasonAvgUpdated' : IDL.Null,
    'TwoMinSuspension' : IDL.Null,
  });
  const FeedEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'playerId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'matchId' : IDL.Opt(IDL.Nat),
    'statValue' : IDL.Opt(IDL.Int),
    'eventType' : FeedEventType,
  });
  const Position = IDL.Variant({
    'Linje' : IDL.Null,
    'VenstreKant' : IDL.Null,
    'Keeper' : IDL.Null,
    'Bakspiller' : IDL.Null,
    'HoyreKant' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'nationality' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'jerseyNumber' : IDL.Opt(IDL.Nat),
    'imageUrl' : IDL.Opt(IDL.Text),
    'teamId' : IDL.Nat,
    'position' : Position,
  });
  const MatchStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Finished' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : MatchStatus,
    'venue' : IDL.Opt(IDL.Text),
    'awayTeamId' : IDL.Nat,
    'homeTeamId' : IDL.Nat,
    'competition' : IDL.Text,
  });
  const PlayerMatchStats = IDL.Record({
    'id' : IDL.Nat,
    'blueCards' : IDL.Opt(IDL.Nat),
    'minutesPlayed' : IDL.Opt(IDL.Nat),
    'assists' : IDL.Opt(IDL.Nat),
    'twoMinSuspensions' : IDL.Opt(IDL.Nat),
    'playerId' : IDL.Nat,
    'sevenMeterGoals' : IDL.Opt(IDL.Nat),
    'yellowCards' : IDL.Opt(IDL.Nat),
    'turnovers' : IDL.Opt(IDL.Nat),
    'sevenMeterAttempts' : IDL.Opt(IDL.Nat),
    'saves' : IDL.Opt(IDL.Nat),
    'shotPct' : IDL.Opt(IDL.Float64),
    'shots' : IDL.Opt(IDL.Nat),
    'matchId' : IDL.Nat,
    'goals' : IDL.Opt(IDL.Nat),
    'savePct' : IDL.Opt(IDL.Float64),
    'redCards' : IDL.Opt(IDL.Nat),
  });
  const ProfixioStatus = IDL.Record({
    'dataSource' : IDL.Text,
    'liveStatsCount' : IDL.Nat,
    'isLive' : IDL.Bool,
    'message' : IDL.Text,
    'lastSync' : IDL.Opt(IDL.Int),
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'goalDifference' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'matchesPlayed' : IDL.Opt(IDL.Nat),
    'standingsRank' : IDL.Opt(IDL.Nat),
    'points' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    'followPlayer' : IDL.Func([IDL.Nat], [], []),
    'getAllPlayerSeasonStats' : IDL.Func(
        [],
        [IDL.Vec(PlayerSeasonStats)],
        ['query'],
      ),
    'getDataStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'playersWithStats' : IDL.Nat,
            'dataSource' : IDL.Text,
            'liveStatsCount' : IDL.Nat,
            'playerCount' : IDL.Nat,
            'teamCount' : IDL.Nat,
            'statsSource' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getFeedEvents' : IDL.Func([], [IDL.Vec(FeedEvent)], ['query']),
    'getFollowedPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getNextMatchForTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerMatchStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PlayerMatchStats)],
        ['query'],
      ),
    'getPlayerSeasonStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerSeasonStats)],
        ['query'],
      ),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getProfixioStatus' : IDL.Func([], [ProfixioStatus], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getUpcomingMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'initUserFollows' : IDL.Func([], [], []),
    'isFollowing' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'refreshFromProfixio' : IDL.Func([], [IDL.Text], []),
    'refreshPlayerStats' : IDL.Func([], [IDL.Text], []),
    'searchPlayers' : IDL.Func([IDL.Text], [IDL.Vec(Player)], ['query']),
    'searchTeams' : IDL.Func([IDL.Text], [IDL.Vec(Team)], ['query']),
    'unfollowPlayer' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };