/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProfixioStatus {
    dataSource: string;
    liveStatsCount: bigint;
    isLive: boolean;
    message: string;
    lastSync?: bigint;
}
export interface PlayerMatchStats {
    id: bigint;
    blueCards?: bigint;
    minutesPlayed?: bigint;
    assists?: bigint;
    twoMinSuspensions?: bigint;
    playerId: bigint;
    sevenMeterGoals?: bigint;
    yellowCards?: bigint;
    turnovers?: bigint;
    sevenMeterAttempts?: bigint;
    saves?: bigint;
    shotPct?: number;
    shots?: bigint;
    matchId: bigint;
    goals?: bigint;
    savePct?: number;
    redCards?: bigint;
}
export interface Player {
    id: bigint;
    name: string;
    slug: string;
    nationality?: string;
    isActive: boolean;
    jerseyNumber?: bigint;
    imageUrl?: string;
    teamId: bigint;
    position: Position;
}
export interface Team {
    id: bigint;
    goalDifference?: bigint;
    name: string;
    slug: string;
    logoUrl?: string;
    matchesPlayed?: bigint;
    standingsRank?: bigint;
    points?: bigint;
}
export interface FeedEvent {
    id: bigint;
    title: string;
    userId: Principal;
    playerId: bigint;
    createdAt: bigint;
    description: string;
    matchId?: bigint;
    statValue?: bigint;
    eventType: FeedEventType;
}
export interface Match {
    id: bigint;
    startTime: bigint;
    status: MatchStatus;
    venue?: string;
    awayTeamId: bigint;
    homeTeamId: bigint;
    competition: string;
}
export interface PlayerSeasonStats {
    id: bigint;
    mepAvg?: number;
    goalsPerGame?: number;
    technicalFaults?: bigint;
    mepTotal?: number;
    goals7m?: bigint;
    playerId: bigint;
    provoked7m?: bigint;
    fieldShots?: bigint;
    assistsPerGame?: number;
    season: string;
    percent7m?: number;
    fieldGoals?: bigint;
    totalYellowCards?: bigint;
    shots7m?: bigint;
    totalSaves?: bigint;
    totalShots?: bigint;
    totalGoals?: bigint;
    awarded7m?: bigint;
    matchesPlayed: bigint;
    fieldGoalPercent?: number;
    totalAssists?: bigint;
    totalRedCards?: bigint;
    shootingPercent?: number;
    totalTwoMin?: bigint;
    totalMinutes?: bigint;
}
export enum FeedEventType {
    NextMatch = "NextMatch",
    GoalsScored = "GoalsScored",
    GamePlayed = "GamePlayed",
    MinutesPlayed = "MinutesPlayed",
    YellowCard = "YellowCard",
    SeasonAvgUpdated = "SeasonAvgUpdated",
    TwoMinSuspension = "TwoMinSuspension"
}
export enum MatchStatus {
    Live = "Live",
    Finished = "Finished",
    Upcoming = "Upcoming"
}
export enum Position {
    Linje = "Linje",
    VenstreKant = "VenstreKant",
    Keeper = "Keeper",
    Bakspiller = "Bakspiller",
    HoyreKant = "HoyreKant"
}
export interface backendInterface {
    followPlayer(playerId: bigint): Promise<void>;
    getAllPlayerSeasonStats(): Promise<Array<PlayerSeasonStats>>;
    getDataStatus(): Promise<{
        playersWithStats: bigint;
        dataSource: string;
        liveStatsCount: bigint;
        playerCount: bigint;
        teamCount: bigint;
        statsSource: string;
    }>;
    getFeedEvents(): Promise<Array<FeedEvent>>;
    getFollowedPlayers(): Promise<Array<Player>>;
    getMatches(): Promise<Array<Match>>;
    getNextMatchForTeam(teamId: bigint): Promise<Match | null>;
    getPlayer(id: bigint): Promise<Player | null>;
    getPlayerCount(): Promise<bigint>;
    getPlayerMatchStats(playerId: bigint): Promise<Array<PlayerMatchStats>>;
    getPlayerSeasonStats(playerId: bigint): Promise<PlayerSeasonStats | null>;
    getPlayers(): Promise<Array<Player>>;
    getPlayersByTeam(teamId: bigint): Promise<Array<Player>>;
    getProfixioStatus(): Promise<ProfixioStatus>;
    getTeam(id: bigint): Promise<Team | null>;
    getTeams(): Promise<Array<Team>>;
    getUpcomingMatches(): Promise<Array<Match>>;
    initUserFollows(): Promise<void>;
    isFollowing(playerId: bigint): Promise<boolean>;
    refreshFromProfixio(): Promise<string>;
    refreshPlayerStats(): Promise<string>;
    searchPlayers(term: string): Promise<Array<Player>>;
    searchTeams(term: string): Promise<Array<Team>>;
    unfollowPlayer(playerId: bigint): Promise<void>;
}
import type { FeedEvent as _FeedEvent, FeedEventType as _FeedEventType, Match as _Match, MatchStatus as _MatchStatus, Player as _Player, PlayerMatchStats as _PlayerMatchStats, PlayerSeasonStats as _PlayerSeasonStats, Position as _Position, ProfixioStatus as _ProfixioStatus, Team as _Team } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async followPlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followPlayer(arg0);
            return result;
        }
    }
    async getAllPlayerSeasonStats(): Promise<Array<PlayerSeasonStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerSeasonStats();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerSeasonStats();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDataStatus(): Promise<{
        playersWithStats: bigint;
        dataSource: string;
        liveStatsCount: bigint;
        playerCount: bigint;
        teamCount: bigint;
        statsSource: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataStatus();
            return result;
        }
    }
    async getFeedEvents(): Promise<Array<FeedEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedEvents();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedEvents();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowedPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowedPlayers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowedPlayers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextMatchForTeam(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextMatchForTeam(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextMatchForTeam(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: bigint): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerCount();
            return result;
        }
    }
    async getPlayerMatchStats(arg0: bigint): Promise<Array<PlayerMatchStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerMatchStats(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerMatchStats(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerSeasonStats(arg0: bigint): Promise<PlayerSeasonStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerSeasonStats(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerSeasonStats(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTeam(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTeam(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTeam(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfixioStatus(): Promise<ProfixioStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfixioStatus();
                return from_candid_ProfixioStatus_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfixioStatus();
            return from_candid_ProfixioStatus_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: bigint): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingMatches();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingMatches();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async initUserFollows(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initUserFollows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initUserFollows();
            return result;
        }
    }
    async isFollowing(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0);
            return result;
        }
    }
    async refreshFromProfixio(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshFromProfixio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshFromProfixio();
            return result;
        }
    }
    async refreshPlayerStats(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshPlayerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshPlayerStats();
            return result;
        }
    }
    async searchPlayers(arg0: string): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlayers(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlayers(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTeams(arg0: string): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeams(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeams(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfollowPlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowPlayer(arg0);
            return result;
        }
    }
}
function from_candid_FeedEventType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedEventType): FeedEventType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FeedEvent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedEvent): FeedEvent {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerMatchStats_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerMatchStats): PlayerMatchStats {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerSeasonStats_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerSeasonStats): PlayerSeasonStats {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ProfixioStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfixioStatus): ProfixioStatus {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : from_candid_Player_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerSeasonStats]): PlayerSeasonStats | null {
    return value.length === 0 ? null : from_candid_PlayerSeasonStats_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : from_candid_Team_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    slug: string;
    nationality: [] | [string];
    isActive: boolean;
    jerseyNumber: [] | [bigint];
    imageUrl: [] | [string];
    teamId: bigint;
    position: _Position;
}): {
    id: bigint;
    name: string;
    slug: string;
    nationality?: string;
    isActive: boolean;
    jerseyNumber?: bigint;
    imageUrl?: string;
    teamId: bigint;
    position: Position;
} {
    return {
        id: value.id,
        name: value.name,
        slug: value.slug,
        nationality: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.nationality)),
        isActive: value.isActive,
        jerseyNumber: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.jerseyNumber)),
        imageUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.imageUrl)),
        teamId: value.teamId,
        position: from_candid_Position_n16(_uploadFile, _downloadFile, value.position)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _MatchStatus;
    venue: [] | [string];
    awayTeamId: bigint;
    homeTeamId: bigint;
    competition: string;
}): {
    id: bigint;
    startTime: bigint;
    status: MatchStatus;
    venue?: string;
    awayTeamId: bigint;
    homeTeamId: bigint;
    competition: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_MatchStatus_n21(_uploadFile, _downloadFile, value.status),
        venue: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.venue)),
        awayTeamId: value.awayTeamId,
        homeTeamId: value.homeTeamId,
        competition: value.competition
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blueCards: [] | [bigint];
    minutesPlayed: [] | [bigint];
    assists: [] | [bigint];
    twoMinSuspensions: [] | [bigint];
    playerId: bigint;
    sevenMeterGoals: [] | [bigint];
    yellowCards: [] | [bigint];
    turnovers: [] | [bigint];
    sevenMeterAttempts: [] | [bigint];
    saves: [] | [bigint];
    shotPct: [] | [number];
    shots: [] | [bigint];
    matchId: bigint;
    goals: [] | [bigint];
    savePct: [] | [number];
    redCards: [] | [bigint];
}): {
    id: bigint;
    blueCards?: bigint;
    minutesPlayed?: bigint;
    assists?: bigint;
    twoMinSuspensions?: bigint;
    playerId: bigint;
    sevenMeterGoals?: bigint;
    yellowCards?: bigint;
    turnovers?: bigint;
    sevenMeterAttempts?: bigint;
    saves?: bigint;
    shotPct?: number;
    shots?: bigint;
    matchId: bigint;
    goals?: bigint;
    savePct?: number;
    redCards?: bigint;
} {
    return {
        id: value.id,
        blueCards: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.blueCards)),
        minutesPlayed: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.minutesPlayed)),
        assists: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.assists)),
        twoMinSuspensions: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.twoMinSuspensions)),
        playerId: value.playerId,
        sevenMeterGoals: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sevenMeterGoals)),
        yellowCards: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.yellowCards)),
        turnovers: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.turnovers)),
        sevenMeterAttempts: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.sevenMeterAttempts)),
        saves: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.saves)),
        shotPct: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.shotPct)),
        shots: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.shots)),
        matchId: value.matchId,
        goals: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.goals)),
        savePct: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.savePct)),
        redCards: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.redCards))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mepAvg: [] | [number];
    goalsPerGame: [] | [number];
    technicalFaults: [] | [bigint];
    mepTotal: [] | [number];
    goals7m: [] | [bigint];
    playerId: bigint;
    provoked7m: [] | [bigint];
    fieldShots: [] | [bigint];
    assistsPerGame: [] | [number];
    season: string;
    percent7m: [] | [number];
    fieldGoals: [] | [bigint];
    totalYellowCards: [] | [bigint];
    shots7m: [] | [bigint];
    totalSaves: [] | [bigint];
    totalShots: [] | [bigint];
    totalGoals: [] | [bigint];
    awarded7m: [] | [bigint];
    matchesPlayed: bigint;
    fieldGoalPercent: [] | [number];
    totalAssists: [] | [bigint];
    totalRedCards: [] | [bigint];
    shootingPercent: [] | [number];
    totalTwoMin: [] | [bigint];
    totalMinutes: [] | [bigint];
}): {
    id: bigint;
    mepAvg?: number;
    goalsPerGame?: number;
    technicalFaults?: bigint;
    mepTotal?: number;
    goals7m?: bigint;
    playerId: bigint;
    provoked7m?: bigint;
    fieldShots?: bigint;
    assistsPerGame?: number;
    season: string;
    percent7m?: number;
    fieldGoals?: bigint;
    totalYellowCards?: bigint;
    shots7m?: bigint;
    totalSaves?: bigint;
    totalShots?: bigint;
    totalGoals?: bigint;
    awarded7m?: bigint;
    matchesPlayed: bigint;
    fieldGoalPercent?: number;
    totalAssists?: bigint;
    totalRedCards?: bigint;
    shootingPercent?: number;
    totalTwoMin?: bigint;
    totalMinutes?: bigint;
} {
    return {
        id: value.id,
        mepAvg: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mepAvg)),
        goalsPerGame: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.goalsPerGame)),
        technicalFaults: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.technicalFaults)),
        mepTotal: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.mepTotal)),
        goals7m: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.goals7m)),
        playerId: value.playerId,
        provoked7m: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.provoked7m)),
        fieldShots: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.fieldShots)),
        assistsPerGame: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.assistsPerGame)),
        season: value.season,
        percent7m: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.percent7m)),
        fieldGoals: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.fieldGoals)),
        totalYellowCards: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalYellowCards)),
        shots7m: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.shots7m)),
        totalSaves: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalSaves)),
        totalShots: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalShots)),
        totalGoals: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalGoals)),
        awarded7m: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.awarded7m)),
        matchesPlayed: value.matchesPlayed,
        fieldGoalPercent: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.fieldGoalPercent)),
        totalAssists: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalAssists)),
        totalRedCards: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalRedCards)),
        shootingPercent: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.shootingPercent)),
        totalTwoMin: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalTwoMin)),
        totalMinutes: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.totalMinutes))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dataSource: string;
    liveStatsCount: bigint;
    isLive: boolean;
    message: string;
    lastSync: [] | [bigint];
}): {
    dataSource: string;
    liveStatsCount: bigint;
    isLive: boolean;
    message: string;
    lastSync?: bigint;
} {
    return {
        dataSource: value.dataSource,
        liveStatsCount: value.liveStatsCount,
        isLive: value.isLive,
        message: value.message,
        lastSync: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.lastSync))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    goalDifference: [] | [bigint];
    name: string;
    slug: string;
    logoUrl: [] | [string];
    matchesPlayed: [] | [bigint];
    standingsRank: [] | [bigint];
    points: [] | [bigint];
}): {
    id: bigint;
    goalDifference?: bigint;
    name: string;
    slug: string;
    logoUrl?: string;
    matchesPlayed?: bigint;
    standingsRank?: bigint;
    points?: bigint;
} {
    return {
        id: value.id,
        goalDifference: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.goalDifference)),
        name: value.name,
        slug: value.slug,
        logoUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.logoUrl)),
        matchesPlayed: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.matchesPlayed)),
        standingsRank: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.standingsRank)),
        points: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.points))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: Principal;
    playerId: bigint;
    createdAt: bigint;
    description: string;
    matchId: [] | [bigint];
    statValue: [] | [bigint];
    eventType: _FeedEventType;
}): {
    id: bigint;
    title: string;
    userId: Principal;
    playerId: bigint;
    createdAt: bigint;
    description: string;
    matchId?: bigint;
    statValue?: bigint;
    eventType: FeedEventType;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        playerId: value.playerId,
        createdAt: value.createdAt,
        description: value.description,
        matchId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.matchId)),
        statValue: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.statValue)),
        eventType: from_candid_FeedEventType_n10(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NextMatch: null;
} | {
    GoalsScored: null;
} | {
    GamePlayed: null;
} | {
    MinutesPlayed: null;
} | {
    YellowCard: null;
} | {
    SeasonAvgUpdated: null;
} | {
    TwoMinSuspension: null;
}): FeedEventType {
    return "NextMatch" in value ? FeedEventType.NextMatch : "GoalsScored" in value ? FeedEventType.GoalsScored : "GamePlayed" in value ? FeedEventType.GamePlayed : "MinutesPlayed" in value ? FeedEventType.MinutesPlayed : "YellowCard" in value ? FeedEventType.YellowCard : "SeasonAvgUpdated" in value ? FeedEventType.SeasonAvgUpdated : "TwoMinSuspension" in value ? FeedEventType.TwoMinSuspension : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Linje: null;
} | {
    VenstreKant: null;
} | {
    Keeper: null;
} | {
    Bakspiller: null;
} | {
    HoyreKant: null;
}): Position {
    return "Linje" in value ? Position.Linje : "VenstreKant" in value ? Position.VenstreKant : "Keeper" in value ? Position.Keeper : "Bakspiller" in value ? Position.Bakspiller : "HoyreKant" in value ? Position.HoyreKant : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Live: null;
} | {
    Finished: null;
} | {
    Upcoming: null;
}): MatchStatus {
    return "Live" in value ? MatchStatus.Live : "Finished" in value ? MatchStatus.Finished : "Upcoming" in value ? MatchStatus.Upcoming : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerSeasonStats>): Array<PlayerSeasonStats> {
    return value.map((x)=>from_candid_PlayerSeasonStats_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerMatchStats>): Array<PlayerMatchStats> {
    return value.map((x)=>from_candid_PlayerMatchStats_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedEvent>): Array<FeedEvent> {
    return value.map((x)=>from_candid_FeedEvent_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
